### ISSUE TITLE
Someone ripping off your blog post content.

### ISSUE THREAD

**Issue by sjwaight** [ash-jc-allen/laravel-mailboxlayer#18]
Ash - saw that you have published a post on this on dev.to here: https://dev.to/ashallendesign/how-to-validate-email-addresses-using-laravel-mailbox-layer-30i2

As an FYI I came across your content completely copied here: https://tuts.dizzycoding.com/how-to-validate-email-addresses-using-laravel-mailbox-layer/ 

I've previously had problems with this site using content without consent and had to reach out to Namecheap who host the website as there is no way to contact the site owner. It looks like all the content is straight copies of other people's content. For some reason Namecheap won't take the site down, but it appears that they will get content blocked at an individual level.

If you feel passionately about this you might want to raise a DMCA take down via this process: https://support.namecheap.com/index.php?/Tickets/Submit/RenderForm/228

**Comment by ash-jc-allen** [comment]
Hey @sjwaight! Thanks, I really appreciate you letting me know about this. I've had similar issues to this in the past, and I've never had much luck being able to get content taken down either.

I'll check out the DMCA takedown form now and see if I can get anywhere with it 🙂
